

mybatis:
  mapper-locations: classpath:mapping/*.xml

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/miaosha?characterEncoding=utf-8&useSSL=false
    username: root
    password: Aa123456
    name: miaosha
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8090
#druid 数据源